#!/bin/sh

set -e

export PREFS_SQL_MYSQL_TEST_CONFIG='{"prefs":{"sql":{"mysql":{"adapter": "mysql", "host":"localhost","username":"root","password":"r00t","dbname":"test","charset":"utf-8"}}}}'
export PREFS_SQL_MYSQLI_TEST_CONFIG='{"prefs":{"sql":{"mysqli":{"adapter": "mysqli", "host":"localhost","username":"root","password":"r00t","dbname":"test","charset":"utf-8"}}}}'
export PREFS_SQL_PDO_MYSQL_TEST_CONFIG='{"prefs":{"sql":{"pdo_mysql":{"adapter": "pdo_mysql", "host":"localhost","username":"root","password":"r00t","dbname":"test","charset":"utf-8"}}}}'
export PREFS_SQL_PDO_PGSQL_TEST_CONFIG='{"prefs":{"sql":{"pdo_pgsql":{"adapter": "pdo_pgsql", "host":"localhost","username":"test","password":"test","dbname":"test","charset":"utf-8"}}}}'

mysql -e "create database IF NOT EXISTS test; ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'r00t';" -uroot
su postgres --command "psql -c \"CREATE USER test WITH PASSWORD 'test';\""
su postgres --command "psql -c \"CREATE DATABASE test OWNER test;\""

cd Horde_Prefs*/test/./Horde/Prefs

# We drop privileges to run tests
touch .phpunit.result.cache
chown www-data:www-data .phpunit.result.cache
su www-data --preserve-environment --shell /bin/sh --command 'phpunit -v .'
